# Generated by Django 4.2.2 on 2023-07-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rfq',
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quotation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('quotation', 'quotation'), ('rejected', 'rejected'), ('ordered', 'ordered')], default='quotation', max_length=10),
        ),
        migrations.DeleteModel(
            name='Rfq',
        ),
        migrations.DeleteModel(
            name='RfqItem',
        ),
    ]
